digraph Computegraph { tooltip = "/"
    nslimit=125 margin=36 ranksep = 2 labelloc="t" label=<<FONT POINT-SIZE="36" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="64" FACE="Helvetica"><B><I>Computation Graph</I></B></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">arrays:</TD><TD CELLPADDING="1" ALIGN="LEFT">21</TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">30.457 Mops</TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">operators:</TD><TD CELLPADDING="1" ALIGN="LEFT">9</TD></TR></TABLE></FONT>>
    subgraph "cluster_conv1d_1" { style=rounded bgcolor="#E9EDF2" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>conv1d_1</I></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">4.267 Mops</TD></TR></TABLE></FONT>>
        "conv1d_1/Relu" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>Relu</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>float[1×1×844×64]</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"conv1d_1/Relu"</FONT></TD></TR></TABLE></FONT>> tooltip="conv1d_1/Relu" shape=box style=filled fillcolor="#F5F5F5" fontcolor="#000000DD"];
        op00001 [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="i0">0</TD><TD PORT="i1">1</TD><TD PORT="i2">2</TD></TR></TABLE></TD></TR><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><B>Conv</B></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">func:</TD><TD CELLPADDING="1" ALIGN="LEFT">ReLU</TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">4.267 Mops</TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">padding:</TD><TD CELLPADDING="1" ALIGN="LEFT">valid</TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">stride:</TD><TD CELLPADDING="1" ALIGN="LEFT">1×1</TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="o0"></TD></TR></TABLE></TD></TR></TABLE></FONT>> tooltip=" " shape=box margin=0 style=filled fillcolor="#C53929" fontcolor="#FFFFFFDD"];
    subgraph "cluster_Relu" { style=rounded bgcolor="#ECF5E1" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>Relu</I></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">4.267 Mops</TD></TR></TABLE></FONT>>
    }
    subgraph "cluster_conv1d" { style=rounded bgcolor="#E9EDF2" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>conv1d</I></FONT></TD></TR></TABLE></FONT>>
        "conv1d_1/conv1d/ExpandDims" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>ExpandDims</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>float[1×1×846×13]</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"conv1d_1/conv1d/ExpandDims"</FONT></TD></TR></TABLE></FONT>> tooltip="conv1d_1/conv1d/ExpandDims" shape=box style=filled fillcolor="#F5F5F5" fontcolor="#000000DD"];
        op00000 [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="i0">0</TD><TD PORT="i1">1</TD></TR></TABLE></TD></TR><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><B>Reshape</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="o0"></TD></TR></TABLE></TD></TR></TABLE></FONT>> tooltip=" " shape=box margin=0 style=filled fillcolor="#DB4437" fontcolor="#FFFFFFDD"];
    subgraph "cluster_ExpandDims" { style=rounded bgcolor="#FDE8E3" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>ExpandDims</I></FONT></TD></TR></TABLE></FONT>>
        "conv1d_1/conv1d/ExpandDims/dim_0" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2"> </TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>dim_0</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>int32[1×4] = {1, 1, 846, 13}</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"conv1d_1/conv1d/ExpandDims/dim_0"</FONT></TD></TR></TABLE></FONT>> tooltip="conv1d_1/conv1d/ExpandDims/dim_0" shape=cylinder style=filled fillcolor="#4285F4" fontcolor="#FFFFFFDD"];
    subgraph "cluster_dim_0" { style=rounded bgcolor="#EFEBE5" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>dim_0</I></FONT></TD></TR></TABLE></FONT>>
    }
    }
        "conv1d_1/conv1d/ExpandDims_1" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2"> </TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>ExpandDims_1</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>float[64×1×3×13]</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"> = {-0.088, -0.188 … -0.133, 0.066}</TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"conv1d_1/conv1d/ExpandDims_1"</FONT></TD></TR></TABLE></FONT>> tooltip="conv1d_1/conv1d/ExpandDims_1" shape=cylinder style=filled fillcolor="#4285F4" fontcolor="#FFFFFFDD"];
    subgraph "cluster_ExpandDims_1" { style=rounded bgcolor="#FDE8E3" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>ExpandDims_1</I></FONT></TD></TR></TABLE></FONT>>
    }
    }
        "conv1d_1/conv1d_bias" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2"> </TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>conv1d_bias</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>float[64]</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"> = {-0.138, -0.007 … -0.033, 0.039}</TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"conv1d_1/conv1d_bias"</FONT></TD></TR></TABLE></FONT>> tooltip="conv1d_1/conv1d_bias" shape=cylinder style=filled fillcolor="#4285F4" fontcolor="#FFFFFFDD"];
    subgraph "cluster_conv1d_bias" { style=rounded bgcolor="#EBFBF4" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>conv1d_bias</I></FONT></TD></TR></TABLE></FONT>>
    }
    }
        "conv1d_1_input" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>conv1d_1_input</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>float[1×846×13]</B></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">minmax:</TD><TD CELLPADDING="1" ALIGN="LEFT">[0, 255]</TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"conv1d_1_input"</FONT></TD></TR></TABLE></FONT>> tooltip="conv1d_1_input" shape=invhouse style=filled fillcolor="#9E9E9E" fontcolor="#000000DD"];
    subgraph "cluster_conv1d_1_input" { style=rounded bgcolor="#F4EBE8" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>conv1d_1_input</I></FONT></TD></TR></TABLE></FONT>>
    }
    subgraph "cluster_conv1d_2" { style=rounded bgcolor="#E9EDF2" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>conv1d_2</I></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">20.747 Mops</TD></TR></TABLE></FONT>>
    subgraph "cluster_conv1d" { style=rounded bgcolor="#E9EDF2" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>conv1d</I></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">20.747 Mops</TD></TR></TABLE></FONT>>
        "conv1d_2/conv1d/ExpandDims_1" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2"> </TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>ExpandDims_1</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>float[64×1×3×64]</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"> = {-0.013, -0.015 … -0.046, -0.148}</TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"conv1d_2/conv1d/ExpandDims_1"</FONT></TD></TR></TABLE></FONT>> tooltip="conv1d_2/conv1d/ExpandDims_1" shape=cylinder style=filled fillcolor="#4285F4" fontcolor="#FFFFFFDD"];
    subgraph "cluster_ExpandDims_1" { style=rounded bgcolor="#FDE8E3" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>ExpandDims_1</I></FONT></TD></TR></TABLE></FONT>>
    }
        "conv1d_2/conv1d/Squeeze" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>Squeeze</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>float[1×1×842×64]</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"conv1d_2/conv1d/Squeeze"</FONT></TD></TR></TABLE></FONT>> tooltip="conv1d_2/conv1d/Squeeze" shape=box style=filled fillcolor="#F5F5F5" fontcolor="#000000DD"];
        op00002 [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="i0">0</TD><TD PORT="i1">1</TD><TD PORT="i2">2</TD></TR></TABLE></TD></TR><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><B>Conv</B></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">func:</TD><TD CELLPADDING="1" ALIGN="LEFT">ReLU</TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">20.747 Mops</TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">padding:</TD><TD CELLPADDING="1" ALIGN="LEFT">valid</TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">stride:</TD><TD CELLPADDING="1" ALIGN="LEFT">1×1</TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="o0"></TD></TR></TABLE></TD></TR></TABLE></FONT>> tooltip=" " shape=box margin=0 style=filled fillcolor="#C53929" fontcolor="#FFFFFFDD"];
    subgraph "cluster_Squeeze" { style=rounded bgcolor="#FEF1FF" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>Squeeze</I></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">20.747 Mops</TD></TR></TABLE></FONT>>
    }
    }
        "conv1d_2/conv1d_bias" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2"> </TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>conv1d_bias</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>float[64]</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"> = {-0.019, -0.026 … 0.041, -0.094}</TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"conv1d_2/conv1d_bias"</FONT></TD></TR></TABLE></FONT>> tooltip="conv1d_2/conv1d_bias" shape=cylinder style=filled fillcolor="#4285F4" fontcolor="#FFFFFFDD"];
    subgraph "cluster_conv1d_bias" { style=rounded bgcolor="#EBFBF4" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>conv1d_bias</I></FONT></TD></TR></TABLE></FONT>>
    }
    }
    subgraph "cluster_dense_1" { style=rounded bgcolor="#EBF1F3" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>dense_1</I></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">5.389 Mops</TD></TR></TABLE></FONT>>
        "dense_1/MatMul_bias" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2"> </TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>MatMul_bias</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>float[100]</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"> = {-0.236, -0.104 … -0.063, -0.120}</TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"dense_1/MatMul_bias"</FONT></TD></TR></TABLE></FONT>> tooltip="dense_1/MatMul_bias" shape=cylinder style=filled fillcolor="#4285F4" fontcolor="#FFFFFFDD"];
    subgraph "cluster_MatMul_bias" { style=rounded bgcolor="#E1EDE7" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>MatMul_bias</I></FONT></TD></TR></TABLE></FONT>>
    }
        "dense_1/Relu" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>Relu</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>float[1×100]</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"dense_1/Relu"</FONT></TD></TR></TABLE></FONT>> tooltip="dense_1/Relu" shape=box style=filled fillcolor="#F5F5F5" fontcolor="#000000DD"];
        op00006 [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="i0">0</TD><TD PORT="i1">1</TD><TD PORT="i2">2</TD></TR></TABLE></TD></TR><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><B>FullyConnected</B></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">func:</TD><TD CELLPADDING="1" ALIGN="LEFT">ReLU</TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">5.389 Mops</TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="o0"></TD></TR></TABLE></TD></TR></TABLE></FONT>> tooltip=" " shape=box margin=0 style=filled fillcolor="#C53929" fontcolor="#FFFFFFDD"];
    subgraph "cluster_Relu" { style=rounded bgcolor="#ECF5E1" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>Relu</I></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">5.389 Mops</TD></TR></TABLE></FONT>>
    }
    subgraph "cluster_kernel" { style=rounded bgcolor="#F7E0F5" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>kernel</I></FONT></TD></TR></TABLE></FONT>>
        "dense_1/kernel/transpose" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2"> </TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>transpose</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>float[100×26944]</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"> = {-0.065, 0.144 … -0.011, -0.003}</TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"dense_1/kernel/transpose"</FONT></TD></TR></TABLE></FONT>> tooltip="dense_1/kernel/transpose" shape=cylinder style=filled fillcolor="#4285F4" fontcolor="#FFFFFFDD"];
    subgraph "cluster_transpose" { style=rounded bgcolor="#E8FEED" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>transpose</I></FONT></TD></TR></TABLE></FONT>>
    }
    }
    }
    subgraph "cluster_dense_2" { style=rounded bgcolor="#EBF1F3" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>dense_2</I></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">530 ops</TD></TR></TABLE></FONT>>
        "dense_2/BiasAdd" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>BiasAdd</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>float[1×2]</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"dense_2/BiasAdd"</FONT></TD></TR></TABLE></FONT>> tooltip="dense_2/BiasAdd" shape=box style=filled fillcolor="#F5F5F5" fontcolor="#000000DD"];
        op00007 [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="i0">0</TD><TD PORT="i1">1</TD><TD PORT="i2">2</TD></TR></TABLE></TD></TR><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><B>FullyConnected</B></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">402 ops</TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="o0"></TD></TR></TABLE></TD></TR></TABLE></FONT>> tooltip=" " shape=box margin=0 style=filled fillcolor="#C53929" fontcolor="#FFFFFFDD"];
    subgraph "cluster_BiasAdd" { style=rounded bgcolor="#EAE8E7" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>BiasAdd</I></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">402 ops</TD></TR></TABLE></FONT>>
    }
        "dense_2/MatMul_bias" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2"> </TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>MatMul_bias</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>float[2] = {0.027, -0.027}</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"dense_2/MatMul_bias"</FONT></TD></TR></TABLE></FONT>> tooltip="dense_2/MatMul_bias" shape=cylinder style=filled fillcolor="#4285F4" fontcolor="#FFFFFFDD"];
    subgraph "cluster_MatMul_bias" { style=rounded bgcolor="#E1EDE7" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>MatMul_bias</I></FONT></TD></TR></TABLE></FONT>>
    }
        "dense_2/Softmax" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>Softmax</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>float[1×2]</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"dense_2/Softmax"</FONT></TD></TR></TABLE></FONT>> tooltip="dense_2/Softmax" shape=house style=filled fillcolor="#9E9E9E" fontcolor="#000000DD"];
        op00008 [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="i0"></TD></TR></TABLE></TD></TR><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><B>Softmax</B></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">128 ops</TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="o0"></TD></TR></TABLE></TD></TR></TABLE></FONT>> tooltip=" " shape=box margin=0 style=filled fillcolor="#DB4437" fontcolor="#FFFFFFDD"];
    subgraph "cluster_Softmax" { style=rounded bgcolor="#E4FFE5" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>Softmax</I></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">128 ops</TD></TR></TABLE></FONT>>
    }
    subgraph "cluster_kernel" { style=rounded bgcolor="#F7E0F5" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>kernel</I></FONT></TD></TR></TABLE></FONT>>
        "dense_2/kernel/transpose" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2"> </TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>transpose</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>float[2×100]</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"> = {-0.009, -0.316 … -0.156, 0.064}</TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"dense_2/kernel/transpose"</FONT></TD></TR></TABLE></FONT>> tooltip="dense_2/kernel/transpose" shape=cylinder style=filled fillcolor="#4285F4" fontcolor="#FFFFFFDD"];
    subgraph "cluster_transpose" { style=rounded bgcolor="#E8FEED" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>transpose</I></FONT></TD></TR></TABLE></FONT>>
    }
    }
    }
    subgraph "cluster_max_pooling1d_1" { style=rounded bgcolor="#EDE4EC" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>max_pooling1d_1</I></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">0.054 Mops</TD></TR></TABLE></FONT>>
        "max_pooling1d_1/ExpandDims" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>ExpandDims</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>float[1×842×1×64]</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"max_pooling1d_1/ExpandDims"</FONT></TD></TR></TABLE></FONT>> tooltip="max_pooling1d_1/ExpandDims" shape=box style=filled fillcolor="#F5F5F5" fontcolor="#000000DD"];
        op00003 [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="i0">0</TD><TD PORT="i1">1</TD></TR></TABLE></TD></TR><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><B>Reshape</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="o0"></TD></TR></TABLE></TD></TR></TABLE></FONT>> tooltip=" " shape=box margin=0 style=filled fillcolor="#DB4437" fontcolor="#FFFFFFDD"];
    subgraph "cluster_ExpandDims" { style=rounded bgcolor="#FDE8E3" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>ExpandDims</I></FONT></TD></TR></TABLE></FONT>>
        "max_pooling1d_1/ExpandDims/dim_0" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2"> </TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>dim_0</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>int32[1×4] = {1, 842, 1, 64}</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"max_pooling1d_1/ExpandDims/dim_0"</FONT></TD></TR></TABLE></FONT>> tooltip="max_pooling1d_1/ExpandDims/dim_0" shape=cylinder style=filled fillcolor="#4285F4" fontcolor="#FFFFFFDD"];
    subgraph "cluster_dim_0" { style=rounded bgcolor="#EFEBE5" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>dim_0</I></FONT></TD></TR></TABLE></FONT>>
    }
    }
        "max_pooling1d_1/MaxPool" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>MaxPool</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>float[1×421×1×64]</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"max_pooling1d_1/MaxPool"</FONT></TD></TR></TABLE></FONT>> tooltip="max_pooling1d_1/MaxPool" shape=box style=filled fillcolor="#F5F5F5" fontcolor="#000000DD"];
        op00004 [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="i0"></TD></TR></TABLE></TD></TR><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><B>MaxPool</B></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">0.054 Mops</TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="o0"></TD></TR></TABLE></TD></TR></TABLE></FONT>> tooltip=" " shape=box margin=0 style=filled fillcolor="#DB4437" fontcolor="#FFFFFFDD"];
    subgraph "cluster_MaxPool" { style=rounded bgcolor="#EFFDED" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>MaxPool</I></FONT></TD></TR><TR><TD CELLPADDING="1" ALIGN="RIGHT">math:</TD><TD CELLPADDING="1" ALIGN="LEFT">0.054 Mops</TD></TR></TABLE></FONT>>
    }
        "max_pooling1d_1/Squeeze" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>Squeeze</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>float[1×421×64]</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"max_pooling1d_1/Squeeze"</FONT></TD></TR></TABLE></FONT>> tooltip="max_pooling1d_1/Squeeze" shape=box style=filled fillcolor="#F5F5F5" fontcolor="#000000DD"];
        op00005 [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" ALIGN="CENTER"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="i0">0</TD><TD PORT="i1">1</TD></TR></TABLE></TD></TR><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><B>Reshape</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="o0"></TD></TR></TABLE></TD></TR></TABLE></FONT>> tooltip=" " shape=box margin=0 style=filled fillcolor="#DB4437" fontcolor="#FFFFFFDD"];
    subgraph "cluster_Squeeze" { style=rounded bgcolor="#FEF1FF" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>Squeeze</I></FONT></TD></TR></TABLE></FONT>>
    }
        "max_pooling1d_1/Squeeze_shape" [label=<<FONT POINT-SIZE="10" FACE="Courier"><TABLE BORDER="0" CELLSPACING="2" CELLPADDING="0"><TR><TD COLSPAN="2"> </TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="16" FACE="Helvetica"><I>Squeeze_shape</I></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="14" FACE="Courier"><B>int32[3] = {1, 421, 64}</B></FONT></TD></TR><TR><TD COLSPAN="2" ALIGN="CENTER"><FONT POINT-SIZE="3" FACE="">"max_pooling1d_1/Squeeze_shape"</FONT></TD></TR></TABLE></FONT>> tooltip="max_pooling1d_1/Squeeze_shape" shape=cylinder style=filled fillcolor="#4285F4" fontcolor="#FFFFFFDD"];
    subgraph "cluster_Squeeze_shape" { style=rounded bgcolor="#FEE8FC" penwidth=0.0 label=<<FONT POINT-SIZE="12" FACE="Courier"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD COLSPAN="2" CELLPADDING="3" ALIGN="CENTER"><FONT POINT-SIZE="18" FACE="Helvetica"><I>Squeeze_shape</I></FONT></TD></TR></TABLE></FONT>>
    }
    }
        "conv1d_1_input":s -> op00000:i0:n [penwidth=4.474985 weight=13.424953];
        "conv1d_1/conv1d/ExpandDims/dim_0" -> op00000:i1:n [penwidth=0.666667 weight=1.000000];
        op00000:o0:s -> "conv1d_1/conv1d/ExpandDims" [penwidth=4.474985 weight=13.424953];
        "conv1d_1/conv1d/ExpandDims" -> op00001:i0:n [penwidth=4.474985 weight=13.424953];
        "conv1d_1/conv1d/ExpandDims_1" -> op00001:i1:n [penwidth=3.761801 weight=1.000000];
        "conv1d_1/conv1d_bias" -> op00001:i2:n [penwidth=2.000000 weight=1.000000];
        op00001:o0:s -> "conv1d_1/Relu" [penwidth=5.240366 weight=15.721099];
        "conv1d_1/Relu" -> op00002:i0:n [penwidth=5.240366 weight=15.721099];
        "conv1d_2/conv1d/ExpandDims_1" -> op00002:i1:n [penwidth=4.528321 weight=1.000000];
        "conv1d_2/conv1d_bias" -> op00002:i2:n [penwidth=2.000000 weight=1.000000];
        op00002:o0:s -> "conv1d_2/conv1d/Squeeze" [penwidth=5.239225 weight=15.717676];
        "conv1d_2/conv1d/Squeeze" -> op00003:i0:n [penwidth=5.239225 weight=15.717676];
        "max_pooling1d_1/ExpandDims/dim_0" -> op00003:i1:n [penwidth=0.666667 weight=1.000000];
        op00003:o0:s -> "max_pooling1d_1/ExpandDims" [penwidth=5.239225 weight=15.717676];
        "max_pooling1d_1/ExpandDims" -> op00004:i0:n [penwidth=5.239225 weight=15.717676];
        op00004:o0:s -> "max_pooling1d_1/MaxPool" [penwidth=4.905892 weight=14.717676];
        "max_pooling1d_1/MaxPool" -> op00005:i0:n [penwidth=4.905892 weight=14.717676];
        "max_pooling1d_1/Squeeze_shape" -> op00005:i1:n [penwidth=0.528321 weight=1.000000];
        op00005:o0:s -> "max_pooling1d_1/Squeeze" [penwidth=4.905892 weight=14.717676];
        "max_pooling1d_1/Squeeze" -> op00006:i0:n [penwidth=4.905892 weight=14.717676];
        "dense_1/kernel/transpose" -> op00006:i1:n [penwidth=7.120511 weight=1.000000];
        "dense_1/MatMul_bias" -> op00006:i2:n [penwidth=2.214619 weight=1.000000];
        op00006:o0:s -> "dense_1/Relu" [penwidth=2.214619 weight=6.643856];
        "dense_1/Relu" -> op00007:i0:n [penwidth=2.214619 weight=6.643856];
        "dense_2/kernel/transpose" -> op00007:i1:n [penwidth=2.547952 weight=1.000000];
        "dense_2/MatMul_bias" -> op00007:i2:n [penwidth=0.500000 weight=1.000000];
        op00007:o0:s -> "dense_2/BiasAdd" [penwidth=0.500000 weight=1.000000];
        "dense_2/BiasAdd" -> op00008:i0:n [penwidth=0.500000 weight=1.000000];
        op00008:o0:s -> "dense_2/Softmax":n [penwidth=0.500000 weight=1.000000];
}
